/* eslint-disable */

export default {
id: 3522949,
title: "Microsoft Fluent Design System Elements Animation",
description: "<p>This is a second shot inspired by recently announced Microsoft Fluent Design system. <br />We combined 5 foundational elements (light, depth, motion, material and scale) that are smoothly and gradually transitioning in one animation. <br />Share your thoughts with us! </p> <p><strong>Press \"L\" to show some love!</strong></p> <p>Don’t forget to follow <a href=\"http://zajno.com\" rel=\"nofollow noreferrer\">Zajno</a> on social media and feel free to drop us a line: <br /><a href=\"https://www.facebook.com/zajnocrew/\" rel=\"nofollow noreferrer\"> Facebook </a>|<a href=\"http://www.uplabs.com/ZajnoCrew\" rel=\"nofollow noreferrer\"> UpLabs</a> | <a href=\"https://www.twitter.com/zajnocrew/\" rel=\"nofollow noreferrer\"> Twitter</a> | <a href=\"https://www.instagram.com/zajno/\" rel=\"nofollow noreferrer\"> Instagram </a> | <a href=\"http://zajno.com\" rel=\"nofollow noreferrer\"> Zajno </a> </p>",
width: 400,
height: 300,
images: {
hidpi: "https://cdn.dribbble.com/users/1468665/screenshots/3522949/ms-fluent_8.gif",
normal: "https://cdn.dribbble.com/users/1468665/screenshots/3522949/ms-fluent_8_1x.gif",
teaser: "https://cdn.dribbble.com/users/1468665/screenshots/3522949/ms-fluent_8_teaser.gif"
},
views_count: 1730,
likes_count: 154,
comments_count: 14,
attachments_count: 0,
rebounds_count: 0,
buckets_count: 11,
created_at: "2017-05-25T12:45:52Z",
updated_at: "2017-05-25T14:27:26Z",
html_url: "https://dribbble.com/shots/3522949-Microsoft-Fluent-Design-System-Elements-Animation",
attachments_url: "https://api.dribbble.com/v1/shots/3522949/attachments",
buckets_url: "https://api.dribbble.com/v1/shots/3522949/buckets",
comments_url: "https://api.dribbble.com/v1/shots/3522949/comments",
likes_url: "https://api.dribbble.com/v1/shots/3522949/likes",
projects_url: "https://api.dribbble.com/v1/shots/3522949/projects",
rebounds_url: "https://api.dribbble.com/v1/shots/3522949/rebounds",
rebound_source_url: "https://api.dribbble.com/v1/shots/3507093",
animated: true,
tags: [
"3d",
"animation",
"c4d",
"clean",
"color",
"design",
"fluent",
"geometry",
"interaction",
"microsoft",
"motion",
"zajno"
],
user: {
id: 1468665,
name: "Igor Pavlinski",
username: "igorogi",
html_url: "https://dribbble.com/igorogi",
avatar_url: "https://cdn.dribbble.com/users/1468665/avatars/normal/bda460c65c18216524fefcf04d0069cb.jpg?1479225894",
bio: "I am designer-animator at <a href=\"https://dribbble.com/Zajno\">@Zajno</a>. Have a project for us? hello@zajno.com",
location: "Austin, Texas",
pro: true,
links: {
twitter: "https://twitter.com/IgorPVLN",
facebook: "https://facebook.com/IgorPVLN"
},
buckets_count: 0,
comments_received_count: 139,
followers_count: 141,
followings_count: 127,
likes_count: 2055,
likes_received_count: 2180,
projects_count: 0,
rebounds_received_count: 3,
shots_count: 14,
teams_count: 1,
can_upload_shot: true,
type: "Player",
pro: false,
buckets_url: "https://api.dribbble.com/v1/users/1468665/buckets",
followers_url: "https://api.dribbble.com/v1/users/1468665/followers",
following_url: "https://api.dribbble.com/v1/users/1468665/following",
likes_url: "https://api.dribbble.com/v1/users/1468665/likes",
projects_url: "https://api.dribbble.com/v1/users/1468665/projects",
shots_url: "https://api.dribbble.com/v1/users/1468665/shots",
teams_url: "https://api.dribbble.com/v1/users/1468665/teams",
created_at: "2016-11-15T15:17:02Z",
updated_at: "2017-05-25T19:58:23Z"
},
team: {
id: 845499,
name: "Zajno Crew",
username: "zajno",
html_url: "https://dribbble.com/zajno",
avatar_url: "https://cdn.dribbble.com/users/845499/avatars/normal/466762084bf3466293fba47c63ba55f7.jpg?1452183579",
bio: "Digital design studio specializing in creating thought-through mobile &amp; web applications that help your business grow. Have a project for us? hello@zajno.com",
location: "Austin, Texas",
links: {
web: "https://zajno.com/",
twitter: "https://twitter.com/ZajnoCrew"
},
buckets_count: 5,
comments_received_count: 6,
followers_count: 2355,
followings_count: 117,
likes_count: 5063,
likes_received_count: 278,
projects_count: 17,
rebounds_received_count: 25,
shots_count: 167,
can_upload_shot: true,
type: "Team",
pro: false,
buckets_url: "https://api.dribbble.com/v1/users/845499/buckets",
followers_url: "https://api.dribbble.com/v1/users/845499/followers",
following_url: "https://api.dribbble.com/v1/users/845499/following",
likes_url: "https://api.dribbble.com/v1/users/845499/likes",
projects_url: "https://api.dribbble.com/v1/users/845499/projects",
shots_url: "https://api.dribbble.com/v1/users/845499/shots",
created_at: "2015-05-12T20:04:33Z",
updated_at: "2017-05-25T17:45:58Z",
members_count: 18,
members_url: "https://api.dribbble.com/v1/teams/845499/members",
team_shots_url: "https://api.dribbble.com/v1/teams/845499/shots"
}
};
